###parameters that should be adjusted most of the time ###

#param_names should be a list of the inerior parameters that are used as a input for the forward model 
param_names: ["Planet_mass"]

#predict name should be the name of the (only one !) parameter you want TabPFN to train to predict from the interior parameters 
predict_name: ["Planet_radius"]

#data_path should be the name of the file containing your data (training and testing) 
#the file should be placed in the data/input folder 
data_path: "test_data.csv"

# test_indices specifies which planets are used to test the predictions capabilities if nothing is specifed 20% will be selected at random
# note that they are the same from run to run for reproducability, you can change the random seed in the specific parameters 
test_indices: [0,0] 


output_format: "plot" # can be set to plot or csv depe




###Specific parameters make sure you understand what they do before changing them ###
batch_size: 100  # how many predictions TabPFN runs in parallel if it is too high you will get a memory error 

random_seed: 42

